#! /bin/bash
#SBATCH -N 12
#SBATCH -t 48:00:00
#SBATCH --ntasks=15

echo "Start of job"
for i in {23..210}
do
    echo "Running script number $i on the background"
	python main.py $i & # Put a function in the background
done
wait
echo "End of job"
