#!/bin/bash
#SBATCH -N 1
#SBATCH -t 20:00:00
#SBATCH --ntasks=7

echo "Start of job"

(python main.py 36; python main.py 51) &
(python main.py 43; python main.py 54) &
(python main.py 44; python main.py 55) &
(python main.py 45; python main.py 56) &
(python main.py 47; python main.py 58) &
(python main.py 49; python main.py 59) &
(python main.py 50; python main.py 60) &
wait

echo "End of job"