#!/bin/bash

echo "Start of job"

(python main.py 3; python main.py 29) &
(python main.py 7; python main.py 34) &
(python main.py 8; python main.py 35) &
(python main.py 9; python main.py 36) &
(python main.py 14; python main.py 37) &
(python main.py 25; python main.py 38) &
(python main.py 26; python main.py 39) &
wait

echo "End of job"