#!/bin/bash

echo "Start of job"

(python main.py 58; python main.py 65; python main.py 72; python main.py 79; python main.py 86; python main.py 93) &
(python main.py 59; python main.py 66; python main.py 73; python main.py 80; python main.py 87; python main.py 94) &
(python main.py 60; python main.py 67; python main.py 74; python main.py 81; python main.py 88; python main.py 95) &
(python main.py 61; python main.py 68; python main.py 75; python main.py 82; python main.py 89; python main.py 96) &
(python main.py 62; python main.py 69; python main.py 76; python main.py 83; python main.py 90; python main.py 97) &
(python main.py 63; python main.py 70; python main.py 77; python main.py 84; python main.py 91; python main.py 98) &
(python main.py 64; python main.py 71; python main.py 78; python main.py 85; python main.py 92; python main.py 99) &
wait

echo "End of job"